/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TkAppRoot {
    }
    interface TkAppSplash {
    }
}
export interface TkAppSplashCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTkAppSplashElement;
}
declare global {
    interface HTMLTkAppRootElement extends Components.TkAppRoot, HTMLStencilElement {
    }
    var HTMLTkAppRootElement: {
        prototype: HTMLTkAppRootElement;
        new (): HTMLTkAppRootElement;
    };
    interface HTMLTkAppSplashElement extends Components.TkAppSplash, HTMLStencilElement {
    }
    var HTMLTkAppSplashElement: {
        prototype: HTMLTkAppSplashElement;
        new (): HTMLTkAppSplashElement;
    };
    interface HTMLElementTagNameMap {
        "tk-app-root": HTMLTkAppRootElement;
        "tk-app-splash": HTMLTkAppSplashElement;
    }
}
declare namespace LocalJSX {
    interface TkAppRoot {
    }
    interface TkAppSplash {
        "onRequestLoginAsGuest"?: (event: TkAppSplashCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "tk-app-root": TkAppRoot;
        "tk-app-splash": TkAppSplash;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tk-app-root": LocalJSX.TkAppRoot & JSXBase.HTMLAttributes<HTMLTkAppRootElement>;
            "tk-app-splash": LocalJSX.TkAppSplash & JSXBase.HTMLAttributes<HTMLTkAppSplashElement>;
        }
    }
}
